modLoader = "javafml"
loaderVersion = "[${forgeDependencyVersion},)"
license = "MIT"

[[mods]]
modId = "hexconjuring"
version = "${version}"
displayName = "Hex Conjuring"
logoFile = "icon.png"
authors = "demonpie"
description = '''
Adds patterns that allow you to conjure things from media
'''

[[dependencies.hexconjuring]]
modId = "forge"
mandatory = true
versionRange = "[${forgeDependencyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexconjuring]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexconjuring]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexconjuring]]
modId = "hexcasting"
mandatory = true
versionRange = "[${hexcastingVersion},)"
ordering = "NONE"
side = "BOTH"
