# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.11
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: demonpie
book_id: hexconjuring:hexconjuringbook
default_branch: main
github_repo: hexconjuring
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: HexconjuringModPlugin
hexdoc_plugin_classname: HexconjuringPlugin
java_lang:
    ext: java
    src: java
java_package: net/hexconjuring
mod_display_name: Hex Conjuring
modid: hexconjuring
multiloader: true
package_export_root: doc/src/hexdoc_hexconjuring/_export
package_name: hexdoc-hexconjuring
package_slug: hexdoc_hexconjuring
package_src: doc/src/hexdoc_hexconjuring
pages_url: https://demonpie.github.io/hexconjuring
pattern_regex:
    per_world_value: registerPerWorld
    regex: (?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?
pattern_registry: registry/HexconjuringPatternRegistry.java
